<header style="text-align: center;"><span class="start">ClassTrek Demo</span><br>
</header>

  <table class="table table-striped" style="margin-bottom: 10px;">
    <thead>             
      <tr class="">             
        <th>EMPLID</th> 
        <th>Last Name</th>    
        <th>First Name</th>   
      </tr>             
    </thead>   
	</table>
  <div id="popup-scroll" class="popup-scroll">
	<table class="table table-striped">
	<tbody>
<tr>
	<td id="move_table_1">1234</td>
	<td id="move_table_2">Htet</td>
	<td id="move_table_3">Kaung</td>
</tr>

<tr>
	<td id="move_table_1">2000</td>
	<td id="move_table_2">Midouin</td>
	<td id="move_table_3">Rene</td>
</tr>

<tr>
	<td id="move_table_1">1000</td>
	<td id="move_table_2">Subick</td>
	<td id="move_table_3">Adarsha</td>
</tr>

	</tbody>
</table>
</div>
